name: Metrics (linguagens por commits)
on:
  schedule: [{ cron: "0 6 * * 1" }]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: carlosHDOliveira
          template: classic
          filename: metrics.svg
          base: header
          config_timezone: America/Sao_Paulo

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: percentage
